[[materials]]
id = "hmx"
name = "Октоген"
reference = "https://example.com/hexolite"
comment = "Взрывяатое вещество октоген"
tags = "взрывчатка, октоген"

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
hmx
$#     mid        ro         d       pcj      beta         k         g      sigy
        22     1.891      9.11      42.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
hmx
$#   eosid         a         b        r1        r2      omeg        e0        vo
        23     778.3     7.071       4.2       1.0       0.3      10.5       0.0
"""

[[materials]]
id = "tnt"
name = "Тротил"
reference = "https://example.com/hexolite"
comment = "Взрывяатое вещество тротил"
tags = "взрывчатка, тротил"

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
tnt
$#     mid        ro         d       pcj      beta         k         g      sigy
       111      1.63      6.57      19.3       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
tnt
$#   eosid         a         b        r1        r2      omeg        e0        vo
      1111     371.2     3.231      4.15      0.95       0.3       7.0       0.0
"""

[[materials]]
id = "comp_a3"
name = "Comp A-3 (А-IX-1)"
reference = "https://example.com/hexolite"
comment = "Взрывяатое вещество Comp A-3, аналог отечественного (А-IX-1)"
tags = "взрывчатка, comp a-3"

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
comp a
$#     mid        ro         d       pcj      beta         k         g      sigy
       222      1.65       8.3      30.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
comp a
$#   eosid         a         b        r1        r2      omeg        e0        vo
       222     611.3     10.65       4.4       1.2      0.32       8.9       0.0
"""

[[materials]]
id = "tnt(i&g)"
name = "Тротил (модель кинетики Ли-Тарвера)"
reference = "https://example.com/hexolite"
comment = "Взрывчатое вещество тротил"
tags = "взрывчатка, тротил"

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
tnt
$#     mid        ro        pc        mu     terod     cerod        ym        pr
        11      1.63       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
tnt
$#   eosid         a         b       xp1       xp2      frer         g        r1
        11     3.712  0.032306      4.15      0.95     0.2223.00000E-6     17.98
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
    -0.9311.22653E-5       6.2       3.1       1.0      50.0       0.0       0.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
       0.0       0.01.00000E-52.17200E-5       4.0       0.0      0.07     288.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
      40.0     0.667     0.222       1.2       1.0       0.0
"""
