[[materials]]
id = "hmx"
name = { ru = "Октоген", en = "HMX" }
reference = "https://example.com/hexolite"
comment = { ru = "Взрывчатое вещество октоген", en = "Explosive HMX" }
tags = { ru = ["взрывчатка", "октоген"], en = ["explosive", "hmx"] }

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
hmx
$#     mid        ro         d       pcj      beta         k         g      sigy
        22     1.891      9.11      42.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
hmx
$#   eosid         a         b        r1        r2      omeg        e0        vo
        23     778.3     7.071       4.2       1.0       0.3      10.5       0.0
"""

[[materials]]
id = "tnt"
name = { ru = "Тротил", en = "TNT" }
reference = "https://example.com/hexolite"
comment = { ru = "Взрывчатое вещество тротил", en = "Explosive TNT" }
tags = { ru = ["взрывчатка", "тротил"], en = ["explosive", "tnt"] }

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
tnt
$#     mid        ro         d       pcj      beta         k         g      sigy
       111      1.63      6.57      19.3       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
tnt
$#   eosid         a         b        r1        r2      omeg        e0        vo
      1111     371.2     3.231      4.15      0.95       0.3       7.0       0.0
"""

[[materials]]
id = "comp_a3"
name = { ru = "Comp A-3 (А-IX-1)", en = "Comp A-3 (A-IX-1)" }
reference = "https://example.com/hexolite"
comment = { ru = "Взрывчатое вещество Comp A-3, аналог отечественного (А-IX-1)", en = "Explosive Comp A-3, equivalent of A-IX-1" }
tags = { ru = ["взрывчатка", "comp a-3"], en = ["explosive", "comp a-3"] }

[materials.material]
model = "mat-he-burn"
units = "mm-mg-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
comp a
$#     mid        ro         d       pcj      beta         k         g      sigy
       222      1.65       8.3      30.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "mm-mg-us"
payload = """*EOS_JWL_TITLE
comp a
$#   eosid         a         b        r1        r2      omeg        e0        vo
       222     611.3     10.65       4.4       1.2      0.32       8.9       0.0
"""

[[materials]]
id = "tnt(i&g)"
name = { ru = "Тротил (модель кинетики Ли-Тарвера)", en = "TNT (Lee-Tarver kinetics model)" }
reference = "https://example.com/hexolite"
comment = { ru = "Взрывчатое вещество тротил", en = "Explosive TNT" }
tags = { ru = ["взрывчатка", "тротил"], en = ["explosive", "tnt"] }

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
tnt
$#     mid        ro        pc        mu     terod     cerod        ym        pr
        11      1.63       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
tnt
$#   eosid         a         b       xp1       xp2      frer         g        r1
        11     3.712  0.032306      4.15      0.95     0.2223.00000E-6     17.98
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
    -0.9311.22653E-5       6.2       3.1       1.0      50.0       0.0       0.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
       0.0       0.01.00000E-52.17200E-5       4.0       0.0      0.07     288.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
      40.0     0.667     0.222       1.2       1.0       0.0
"""

[[materials]]
id = "rdx"
name = { ru = "RDX", en = "RDX" }
reference = ""
comment = { ru = "Взрывчатое вещество гексоген", en = "Explosive RDX" }
tags = { ru = ["взрывчатка", "гексоген"], en = ["explosive", "rdx"] }

[materials.material]
model = "mat-he-burn"
units = "cm-g-us"
payload = """*MAT_HIGH_EXPLOSIVE_BURN_TITLE
RDX
$#     mid        ro         d       pcj      beta         k         g      sigy
        22      1.65      0.83       0.3       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-jwl"
units = "cm-g-us"
payload = """*EOS_JWL_TITLE
RDX
$#   eosid         a         b        r1        r2      omeg        e0        vo
        22  9.890848 0.1111902     5.167    1.0458  0.396143     0.094       0.0
"""

[[materials]]
id = "pbx-9501(i&g)"
name = { ru = "PBX 9501 (модель кинетики Ли-Тарвера)", en = "PBX 9501 (Lee-Tarver kinetics model)" }
reference = ""
comment = { ru = "Взрывчатое вещество пластит", en = "Explosive PBX 9501" }
tags = { ru = ["взрывчатка", "пластит"], en = ["explosive", "pbx 9501"] }

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
pbx 9501
$#     mid        ro        pc        mu     terod     cerod        ym        pr
        91       1.8       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
pbx 9501
$#   eosid         a         b       xp1       xp2      frer         g        r1
        91    16.689    0.5969       5.9       2.1     0.6674.50000E-6    7320.0
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
 -0.0526542.46560E-5      14.1      1.41       0.31.40000E11     130.0       2.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
     0.227     0.6671.00000E-52.78060E-5      20.0       0.0     0.095     288.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
     400.0       1.0     0.333       2.0       0.5       0.5
"""

[[materials]]
id = "pbxn-109(i&g)"
name = { ru = "PBXN-109 (модель кинетики Ли-Тарвера)", en = "PBXN-109 (Lee-Tarver kinetics model)" }
reference = ""
comment = { ru = "Взрывчатое вещество PBXN-109", en = "Explosive PBXN-109" }
tags = { ru = ["взрывчатка", "pbxn-109"], en = ["explosive", "pbxn-109"] }

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
PBXN-109
$#   eosid         a         b       xp1       xp2      frer         g        r1
        92    13.413    0.0327       6.0       2.0    0.66672.00000E-6    8817.0
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
   -0.03551.94000E-5      15.0      1.41      0.22    6700.0     403.5       2.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
    0.6667     0.2221.00000E-52.50000E-5       9.0      0.02     0.102     298.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
     230.0       1.0     0.333       3.0       0.5       0.0
"""

[[materials]]
id = "jh-2(i&g)"
name = { ru = "JH-2 (модель кинетики Ли-Тарвера)", en = "JH-2 (Lee-Tarver kinetics model)" }
reference = ""
comment = { ru = "Взрывчатое вещество JH-2, аналог отечественного А-IX-1", en = "Explosive JH-2, equivalent of A-IX-1" }
tags = { ru = ["взрывчатка", "jh-2"], en = ["explosive", "jh-2"] }

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
jh2
$#     mid        ro        pc        mu     terod     cerod        ym        pr
      1111      1.72       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
jh2
$#   eosid         a         b       xp1       xp2      frer         g        r1
      1111     6.125    0.1395       4.5       1.4     0.6672.50000E-6     310.0
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
 -0.0327852.22000E-5      11.3      1.13     0.022   4000000     140.0       2.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
     0.329     0.6671.00000E-52.48700E-5       7.0     0.022      0.09     298.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
    1000.0     0.333     0.067       3.0       1.0       0.0
"""

[[materials]]
id = "ultrafine-tatb(i&g)"
name = { ru = "Ultrafine TATB (модель кинетики Ли-Тарвера)", en = "Ultrafine TATB (Lee-Tarver kinetics model)" }
reference = ""
comment = { ru = "Взрывчатое вещество мелкодисперсный ТАТБ", en = "Explosive ultrafine TATB" }
tags = { ru = ["взрывчатка", "татб"], en = ["explosive", "tatb"] }

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
ultrafine tatb
$#     mid        ro        pc        mu     terod     cerod        ym        pr
      1112       1.8       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
ultrafine tatb
$#   eosid         a         b       xp1       xp2      frer         g        r1
      1112  12.05026  0.602513       6.2       2.2     0.6675.00000E-6    632.07
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
  -0.044722.22000E-5      11.3      1.13     0.071   4000000    2200.0       2.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
     0.667       1.01.00000E-52.48700E-5       7.0      0.22     0.069     298.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
      60.0     0.667     0.667       1.0       1.0       0.8
"""

[[materials]]
id = "lx-17(i&g)"
name = { ru = "LX-17 (модель кинетики Ли-Тарвера)", en = "LX-17 (Lee-Tarver kinetics model)" }
reference = ""
comment = { ru = "Взрывчатое вещество композит LX-17", en = "Explosive LX-17 composite" }
tags = { ru = ["взрывчатка", "композит на основе татб", "lx17"], en = ["explosive", "tatb-based composite", "lx-17"] }

[materials.material]
model = "mat-null"
units = "cm-g-us"
payload = """*MAT_NULL_TITLE
lx17
$#     mid        ro        pc        mu     terod     cerod        ym        pr
      1113     1.905       0.0       0.0       0.0       0.0       0.0       0.0
"""

[materials.eos]
model = "eos-ignition-growth"
units = "cm-g-us"
payload = """*EOS_IGNITION_AND_GROWTH_OF_REACTION_IN_HE_TITLE
lx17
$#   eosid         a         b       xp1       xp2      frer         g        r1
      1113   14.8105    0.6379       6.2       2.2     0.6675.00000E-6     778.1
$#      r2        r3        r5        r6     fmxig      freq     grow1        em
  -0.050312.22000E-5      11.3      1.13      0.02   4000000    4600.0       3.0
$#     ar1       es1       cvp       cvr     eetal     ccrit       enq      tmp0
     0.667       1.01.00000E-52.48700E-5       7.0      0.22     0.069     298.0
$#   grow2       ar2       es2        en     fmxgr     fmngr
      30.0     0.667     0.667       1.0       0.8       0.8
"""
